# site settings
title: Website of Ábel Sinkovics
author: Ábel Sinkovics
description: "Personal website of Ábel Sinkovics"

# build settings
port: 4000
highlighter: rouge
markdown: karmdown
permalink: pretty

